### ISSUE TITLE
Library not found for -lmamearm64-tvos

### ISSUE THREAD

**Issue by aldosolis** [yoshisuga/MAME4iOS#137]
I'm not able to build the projects the following error is shown:

ld: library not found for -lmamearm64-tvos

Any ideas?

![image](https://user-images.githubusercontent.com/1450561/77232232-6777e100-6b65-11ea-8a57-b836ab5ae21d.png)

**Comment by arcticleo** [comment]
I'm guessing you've run in to the same issue I struggled with to get it to build on macOS Catalina. When I ran the commands in the bash script one by one, I realized that make choked because Catalina refused to run file2str and other command line utilities. It was a bit tedious because I don't know a way of giving blank permission, so I kept the System Preferences > Security & Privacy panel open while running make, giving permission as needed. Then after giving all utilities permission, I needed to run make once more, and this time, while it paused execution a few times, it let me say OK, and it then ran through.

**Comment by ToddLa** [comment]
Hmmm I just gave Terminal full permissions. 

But yes make sure you run make-iOS.sh or make-sim.sh first.

**Comment by ToddLa** [comment]
Or in your case make-tvos.sh

**Comment by arcticleo** [comment]
@ToddLa Runnng make-tvos.sh and all the other bash scripts fail by default for me (and I'm guessing for @aldosolis as well) on Catalina because of the new strict security settings, which leads to Xcode not finding the mamearm64-tvos library. However it's it's possible to limp by it by giving the command line utilities permission to run in Security & Privacy.

**Comment by ToddLa** [comment]
Like I said, I only had to give Terminal permission not each tool one by one, damn Catalina!

**Comment by arcticleo** [comment]
@ToddLa Ah, I see. Great tip, thanks. 👏

**Comment by mrjschulte** [comment]
Catalina needs to have terminal privileges granted in order for the compile of the libraries to complete successfully.
