### ISSUE TITLE
Add “Reset to Defaults” in Settings.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#156]
This would delete our plist and go back to defaults.
Should it also....
* delete recent games
* delete favorite games
* delete mame.cfg

**Comment by mrjschulte** [comment]
Nope, only MAME cfg should be reset imho.

**Comment by ToddLa** [comment]
MAME.cfg does not exist. 

What does exist is cfg/default.cfg if you change any global key mappings or settings, they will be in here.

There are also key mappings in cfg/romname.cfg but you can get rid of that by selecting Delete from context menu.

**Comment by rslkr** [comment]
If you don't mind I'd like to say some words about ''Reset to Defaults''
This is one of my wish list for this app.

- delete mame.cfg
There's a ''Reset Game'' in MAME Config Menu / User Interface
I remap it to random button to see how it works. But it just behaved like ''Soft Reset''
It didn't reset what I want.
I want to reset ''Config Menu/Input (This Game)'' in game mode.
I also want to reset the ''Input General''
I'm asking this 'coz I ruined the whole MAME settings before and I had to delete the app.

- delete favorite games
@mrjschulte  I mean no offence please but I think this one is necessary.
I do have a point.
I was curious about this one and I wanna see how many I can add to ''Favorite''
Now over 300 games in favorite, probably i can add more.

I know it's easy to write and ask here That's why I said ''I wish I can help.''

**Comment by ToddLa** [comment]
By MAME.cfg, do you mean cfg/default.cfg I don’t think mame.cfg exists, mame.ini exists, but we should leave that alone.

Yes I think deleting favorites is a good thing, this will option only be used as a blunt hammer. 

The option will be a button in Settings (at the bottom)

It will
* delete our settings plist. 
* delete recents and favorites. 
* delete cfg/mame.cfg
* if you are in a game, remove cfg/ROMNAME.cfg
* restart mame back to game or menu

**Comment by ToddLa** [comment]
It is not as simple as delete files, restart.

Mame writes it cfg files when it exits...

So it is, exit mame, delete cfg, restart mame. 

Not hard, just particular

**Comment by mrjschulte** [comment]
I think the context of the original Issue has grown a bit beyond the original scope of me locking myself out of the tvOS app which is fair enough.

A bold hammer to reset everything in the App to defaults, just as the app would come up for the first time if you had freshly installed it whilst keeping all of your games and game related items, seems like a fair goal.

**Comment by rslkr** [comment]
@ToddLa 

- Input (this Game)
You already did. I can reset to default but it is in the wrong place,
 in my opinion it should be in popup menu game mode or in the settings.

- Input (general)
I couldn't find any solution I checked desktop MAME and web.

@mrjschulte 
Sorry about that nowadays I stuck home, nothing to do :(

**Comment by rslkr** [comment]
If this ''Reset to Defaults'' can be selectable.
That would be very nice.
Like so:

- Delete All (Factory settings)

- Delete Only MAME4IOS Setting or TVOS Settings

- Delete All MAME settings

- Delete Only MAME Input (this Game)

**Comment by rslkr** [comment]
Finally, We got a reset button.Crossed another one off my wish list.Thank you.
I thought it'd be good if its selectable but doesn't matter. For now.
I can delete those files by using the iOS Folder, no problem.
I hope Apple does not remove or block this iOS Folder in the future.

**Comment by ToddLa** [comment]
Being selectable is just to confusing/complex. Reset is a tool you use at last resort, not a “use every day feature”

There are two types of reset...

Global Settings Reset (aka Factory Reset)
`Settings` > `Reset to Defaults`
* restore all MAME4iOS settings to default.
* remove Recent and Favorite games.
* delete any cached Title Images. 
* delete any MAME key mappings or settings. 

Per Game Settings
context menu, select `Delete`, then choose `Delete Settings`. 
* delete any MAME key mappings or settings for game
* delete any hiscores
* delete any saved state.
* delete Title image. 

You can also remove a game totally, context menu `Delete`, choose `Delete All Files`
