### ISSUE TITLE
Add Player 2 start to in-game menu.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#168]
We should add a Coin+Player 2 Start to the in-game menu. 

Should we show P1 and P2 Start on the secondary controller? Or just PN Start?

The only reason not to do this is because space on the menu is crowded, and don’t want to clutter up things. 

We re only tight on space in landscape mode on iPhone or TV, the menu will scroll, so we might need t live with it.

The current only way to do a P2 Start is....
* MENU+R on a second controller
* MENU+R+UP on main controller 
And this can be difficult, non-discoverable.

**Comment by ToddLa** [comment]
If you are running a game with numWays == 2 (ie Asteroids) you cant do a P2 start, because you can’t hit up.

**Comment by rslkr** [comment]
Hi @ToddLa 
**Add Player 2 start to in-game menu** Fine by me. 👍

I don't use 'Coin and Start buttons' for P1 anymore since we have the Coin+Start in the game menu.

If you could add P3 and P4 as well in the game menu and then I guess we won't need these Coin and Start buttons.

**Suggestion:** 
You can rename the first one only '**Coin**', and you can make one more section for '**Select Player(s)**'

When we touch on the '**Coin**' the game menu remains and after that we select player in another menu.

Also more we tap on the Coin section it can show numbers how many coin we add.Like a counter.

I'm not sure this is a bad/good idea or users would confused  or it will be clutter up!!!

**Comment by ToddLa** [comment]
The reason coin+start are combined is for quick, one click play. And to save space in the menu. 

We use a standard UIAlertView so we can’t (easily) add sub menus or pop ups, without doing a custom menu.

**Comment by nuance1979** [comment]
> The reason coin+start are combined is for quick, one click play. And to save space in the menu.
> 
I really like this "coin+start" design, extremely convenient for single player sessions.

**Comment by ToddLa** [comment]
And the wacko MENU+L and MENU+L+UP still work in cases you need it

**Comment by rslkr** [comment]
> The reason coin+start are combined is for quick, one click play. And to save space in the menu.

Yes You are right.

**Comment by ToddLa** [comment]
PR #177 puts a P1 Start and a P2 Start in the menu.
Made room by combining Load State and Save State

**Comment by ToddLa** [comment]
Also ....

`MENU+L2` inserts a P2 `COIN`
`MENU+R2` does a P2 `START`

**Comment by mrjschulte** [comment]
Done and merged into mainline.
