### ISSUE TITLE
Keep the HUD?

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#217]
The main reason for the `HUD` is to tweak Shader params to make useful pre-sets. But it also does useful in-game stuff. 

Should. We make it easier to turn on, or just keep the switch in `Settings` maybe add a toggle to in-game menu?

What other changes should we make to make it more useful?

**Comment by ToddLa** [comment]
From rslkr:

“Can we add the HUD into the OPTION button for easy access? Please.
It can work exactly like MAME Menu
Having one more section on the pop-up MENU won't bother anyone I think.
Especially this one HUD.
I know last time you said ''save space in the menu''
But there is still room on Portrait mode, plus we already scrolling it down/up on the Landscape mode.
Thanks.”

**Comment by rslkr** [comment]
I asked this before and I think this time you could add them. It is the right place.

**P3 Start  P4 Start**

And There are 2 ''**Settings**''  on the HUD, one is too many.(The gear icon and the other Settings)
I'd like to say keep only the gear icon and replace the bottom one with ''Soft Reset''  but It supposed to be a cancel option like ''**Load/Save State**''

Or you can remove the gear icon settings, and make one more menu list icon it can open another list of stuffs like this: #186 
Anyway you always come up with better ideas.

Question: Is this a bug?

When I start any game, I can't use the EXIT button and the other Exit in Option to quit the game!
I have move the joystick left/right to start the game.
(I know its working like this since ''Gridlee'' yes I've been using this App since Gridlee I missed imame though)
One of the previous update that EXIT was working.
This was a good if you tap on the wrong game and want to quit quickly.

**Comment by ToddLa** [comment]
Sounds like you have `Show Info/Warnings` on, and yea you cant exit in this mode!

**Comment by ToddLa** [comment]
The reason `Settings` is both a toolbar icon and a button, is just inertia/lazy/random

* `Settings` is on the toolbar cuz it is kind of important.

* `Settings` is in the expanded `HUD` to be consistent with in-game menu. What I did is copy exactly what is in the in-game menu when the `HUD` is expanded, to be consistent and also I needed two buttons on the row to “look nice”

**Comment by ToddLa** [comment]
...but the `HUD` is its own thing, and can be different from the in-game menu, that is what this issue is about feedback!

The `HUD` is a little more flexible than the in-game menu because it can have multiple buttons in a row, and even colors! Basically it is not limited to what a `UIAlertController` can do. 

The Toolbar at the top of the `HUD` is about as full as it can get. Current items are.....
* Coin
* Start
* Fullscreen Toggle
* Settings
* Expand `HUD`
* Shrink `HUD`

**Comment by rslkr** [comment]
> The Toolbar at the top of the HUD is about as full as it can get.

> Settings is on the toolbar cuz it is kind of important.

Yes, That's right.

> What other changes should we make to make it more useful?

Well, ''**Soft Reset** and **Service(Game's Settings)**'' should be on the HUD I don't know how often you guys using them.
They're very useful and I believe activating them by buttons would be more practical than using the MAME MENU

I wish we have all MAME config. menu on the modern ui design but that's not possible, right!

**Comment by mrjschulte** [comment]
Soft reset could be handy but, to the earlier points made, the HUD is getting a bit cramped.

**Comment by rslkr** [comment]
Hi, mrjschulte 
I did a lot of testing and I thought the **Service** could be useful, it is but,  Not every game has own **Game's Settings**...
It causes a problem on some games. I tried to use on the game called **Asteroid** and the game stuck on kinda error screen!!!
Soft reset and exit the game didn't help. I delete all setting of the game.
So better leave the Service on MAME menu.

and ToddLa please forget about the HUD on in game menu, that's unnecessary, Sorry.

**Comment by ToddLa** [comment]
HUD uses the system Dynamic type, if you make that larger the HUD will get larger.

**Comment by ToddLa** [comment]
...ok UISegmentedControls needed some "hand holding" to properly handle DynamicType! fix is in #227

**Comment by mrjschulte** [comment]
#227 was merged. So closing.
