### ISSUE TITLE
Add support for iCloud auto-syncing

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#249]
Consider adding support for using iCloud as a distributed storage platform to keep games, artwork, save states, themes and hi-scores synced between the different devices (iOS/tvOS/MacOS) running MAME4iOS.

**Comment by mrjschulte** [comment]
@ToddLa might have some thoughts on this....

**Comment by ToddLa** [comment]
# iCloud Sync in MAME4iOS 
I think this might be pretty simple. 

## iCloud option in Settings
* There will be a single check box in Settings to enable `iCloud Sync`
* It can be in the Import and Export group, with Start Server and Import...
* iCloud can be disabled by the user in the iOS Settings app, in this case M4i will just act like the setting is turned off, and will disable the switch to turn it on. 
* The default will be `OFF` (more on that in next section)

## First Launch, OOBE, and TV 
* When M4i is run the first time (or zero ROMs are found) the user is give an option to `Start Server` or `Import ROMs`
* Add another option to this dialog (if iCloud is not globally disabled) asking user to `Turn on iCloud Sync`
* After loading ROMs into M4i on your iPhone (with iCloud enabled) you should be able to run a clean version on another device (iPad, TV, Mac, ....) click `Turn on iCloud Sync` when you get the OOBE alert, and all your ROMs will appear. 

## Source of Truth
There are a few options
* iCloud (when enabled) is the SoT only ROMs from iCloud container will be shown. 
    - when you do a import, ROMs will be copied to iCloud
* iCloud ROMs and local ROMs will both be shown
    - when you do an import where should the ROMs be copied?

**Comment by ToddLa** [comment]
## Automatic Sync vs Explicit Sync.

**Automatic sync** is having only one option `Enable iCloud Sync` and magic happens.

**Explicit Sync** is not having an option, instead there are two buttons or menu items, `Import from iCloud` and `Export to iCloud`

I think the best strategy is to do **Explicit Sync** considering that some builds wont be able to use iCloud because of entitlement issues.

**Comment by mrjschulte** [comment]
This all sounds pretty amazing to have.

**Comment by ToddLa** [comment]
Turns out that tvOS does not support `iCloud documents`, so the only way forward is using `CloudKit`

Explicit sync is still the best plan...

When MAME4iOS is built with a `CloudKit` entitlement you will see a new `iCloud` section in `Settings`
![](https://cdn.discordapp.com/attachments/682362941693231135/767087699353010196/image0.jpg)

`Export to iCloud` will copy all local ROM, Artwork, State files up to the `CloudKit` database. (Only files not already uploaded are copied)

`Import from iCloud` will copy down files from the Cloudkit database. 

`Sync with iCloud` will do both a Import and Export. 

NOTE files are never deleted, only ever copied.

An option to `Erase all Cloud files` can be used to remove all files in `iCloud`.

**Comment by ToddLa** [comment]
PR #263 does this
