### ISSUE TITLE
iPad Pro iOS 14.2 crash on startup

### ISSUE THREAD

**Issue by tomusn83** [yoshisuga/MAME4iOS#270]
Build successful and when run on iPad Pro running iOS 14.2 crashes immediately. Tried with game controller connected and not connected.

Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 2 beyond bounds [0 .. 1]'

#12	0x0000000100bcc2a0 in +[NSUserDefaults(shared) sharedUserDefaults] at /Users/tom/dev/MAME4iOS/xcode/MAME4iOS/ChooseGameController.m:164

**Comment by ToddLa** [comment]
this happens if you dont have the bundleIdentifier set correctly.
bundleIdentifer is assumed to be at least 3 components.

check `MAME4iOS.xcconfig` and make sure `ORG_IDENTIFIER` is of the form `xxx.yyyyyyy` by default is is set to `com.example`

**Comment by ToddLa** [comment]
Crashing is kind of by design (DEBUG build will assert) to let the developer know that the BundleIdentifier is not correct. 

What might be a better thing to do is to not crash, but throw up an alert telling developer that the bundle ident is bad. 

All this bundle ident finickyness is so we can register entitlements, mostly for iCloud import, export, and sync. 
(Widget and TopShelf too, but iCloud is main reason)

**Comment by tomusn83** [comment]
> this happens if you dont have the bundleIdentifier set correctly.
> bundleIdentifer is assumed to be at least 3 components.
> 
> check `MAME4iOS.xcconfig` and make sure `ORG_IDENTIFIER` is of the form `xxx.yyyyyyy` by default is is set to `com.example`

Thanks! I had my org identifier, but not 3 components.
