### ISSUE TITLE
Bubble Bobble II and Bubble Memories (Touch Mouse Mode Enabled)

### ISSUE THREAD

**Issue by Catarax** [yoshisuga/MAME4iOS#281]
Theses games have Touch Mouse Mode enabled at startup for no reason, no possibility to play them with touchscreen at all.

**Comment by ToddLa** [comment]
Is this a new issue?

**Comment by Catarax** [comment]
I started to use MAME4IOS on version 2020.12 and the last one, the games can't be played.

**Comment by ToddLa** [comment]
Yea `Touch Mouse` is enabled because the `MAME` machine for BB2 is asking for LightGun/Mouse.

If you turn off `Settings` > `Game Input` > `Hide Touch D-Pad` you will be able to use the onscreen D-Pad to play.

BB2 (unlike a game like Tempest) want to get get input from a Joystick *and* a Dial.

Maybe `Hide Touch D-Pad` should default to `OFF`

**Comment by ToddLa** [comment]
OR maybe the touch D-Pad should only be hidden when fullscreen

**Comment by Catarax** [comment]
I got to disable the TOUCH ANALOG feature to get it to work, thank you!
