### ISSUE TITLE
Game is missing required ROM or CHD images

### ISSUE THREAD

**Issue by gbrooker** [yoshisuga/MAME4iOS#31]
I've built and run Mame4iOS on my AppleTV. I had to swap around a few controls to get it functioning with my Nimbus, but after that I was able to get it to run galaxians and pacman (galaxian hardware). I haven't been able to load any other games though, asteroids, 1941, galaga, defender and many others just result in the error message "The selected game is missing one or more required ROM or CHD images". I've tried ROMs from multiple sources but always the same message. Are there other files I need to obtain ? I tried to add the samples and artwork from lesbirds distribution, but that didn't help.

**Comment by yoshisuga** [comment]
Hi there! Thanks for trying out the new AppleTV build. I just tried the ROMs you mentioned and they seem to be run ok. You need to make sure that your ROMs are from the 0.139 set - ROMs for the latest version of MAME may not work with this because this is based on a much older version. For those games, you just need the single zip file, no other files are required.

**Comment by gbrooker** [comment]
Thanks, that was exactly it. I ditched all my old ROMs and got hold of the 0.139 set. Thanks so much for the port to AppleTV, it brings back wonderful memories !
