### ISSUE TITLE
can support arm64?

### ISSUE THREAD

**Issue by PugaTang** [yoshisuga/MAME4iOS#6]
Apple will deprecate the armv7 app...

**Comment by yoshisuga** [comment]
Yes, I heard that too and was really bummed about that. I recompiled the MAME library using arm64, and changed the architecture of the app to support arm64. 

The good news is that it works, but the bad news is that it's noticeably slower than the 32-bit binary. The games I tested were Die Hard Arcade and Street Fighter 3 Third Strike, as I know these were demanding in performance. 

I'll make a commit either on master or on a branch with the change. 

I had to compile using OPTIMIZE=0, otherwise it hangs while compiling. I have no idea what that does either :)

**Comment by yoshisuga** [comment]
I created a branch called 'arm64-ios' that will supports arm64.

If anyone is more familiar with compiling a more optimized version please help out :)

**Comment by PugaTang** [comment]
Thank you so much for this! 
But I am sorry for optimization issue.

**Comment by DarrenBranford** [comment]
This is great news!

I have just tested with OPTIMIZE = 1 and have played Street Fighter 3 Third Strike at very nearly 100% speed (it fluctuates slightly between 100% and 98%) without speed hacks on my iPad Air 2 and iPhone 7.

I'm not sure what that setting does either.

**Comment by yoshisuga** [comment]
Thanks @DarrenBranford!! You were right, OPTIMIZE = 1 does result in a noticeable speed improvement! For some reason when I thought I did that, it hung on compilation, but it indeed actually did finish compiling.

I updated the arm64-ios branch with the change to the makefile.

So MAME might live on post-iOS 11! (I remember compiling the MAME binary on iOS 10 beta while at the last WWDC)

**Comment by thededman** [comment]
@yoshisuga  thanks for keeping this version alive. The optimize makes HUGE difference in Cruisn'n USA and World Version as well. Playing Street Fighter 2 is insane, I feel like a kid in the arcade again!

**Comment by yoshisuga** [comment]
No problem @thededman ! I'm glad to be able to keep this alive :)

I merged the arm64-ios branch to master - so closing :)

**Comment by calburitel** [comment]
Hi all. I just wanted to thank you all for keeping this one working on my iPhone 7. MAME4iOS is my favorite emulator and I was sad when I couldn't get it to work on the new XCODE and iOS. I don't really know what I'm doing, but know enough to get this version running smoothly on my devices. Truly, truly, thank you!

**Comment by yoshisuga** [comment]
You're very welcome @calburitel !! I don't know what I'm really doing sometimes, but I just keep trying to get things to work :) I'm glad you were able to get it to work too!
