### ISSUE TITLE
Layout Problems on iPhone X and iPhone XS Mas

### ISSUE THREAD

**Issue by cvogelbusch** [yoshisuga/MAME4iOS#76]
First of it's amazing that you made this for iOS! Thank you! Thank you! Thank you!
I got it to compile for me (XS Max) and my wife (X), but for both of us the layout is off:
On XS Max most things look fine, but the Joystick is off (it's on the screen not in the marked are)
On X everything is off, Joystick area is squeezed, buttons and joystick are above, menu is on the screen.
Would be amazing when fixed :-€
![iPhone XS Max Layout](https://user-images.githubusercontent.com/687205/57063654-3fb92980-6cc4-11e9-8f62-60f98ba36dbf.jpeg)
![iPhone X Layout](https://user-images.githubusercontent.com/687205/57063671-4cd61880-6cc4-11e9-9a28-eff131b9d70e.jpeg)

**Comment by yoshisuga** [comment]
Hi yes, this is a known problem. You can workaround it by changing the layout manually in Settings -> Game Input -> Change Current Layout

**Comment by longbauw** [comment]
Hi guys can some one send me the ipa or deb 
files that already compiled to work with iphone xs max on ios 12.0.1 please

I am jailbroken with chimera on ios 12.0.1

I dont have a mac or the knowhow the compile it my self.

I had the mame4ios emulator running since the beginning on ios 6

This is the first time ever that i cant install the emulator on a ios device and it sucks.

So i hope could help me out.

**Comment by ToddLa** [comment]
All the layout issues should be correct in 2020.1
