### ISSUE TITLE
iPad Pro keyboard support

### ISSUE THREAD

**Issue by blueneogeo** [yoshisuga/MAME4iOS#9]
Allowing keyboard bindings would be fantastic. I hope the pro keyboard allows multiple keypresses?

Also, an option to hide the  on screen controls automatically when the keyboard is attached.

**Comment by yoshisuga** [comment]
Keyboard support is something I've never thought of, but would be nice. I'm not sure if we have API access to "key up" and "key down" events without resorting to overriding functions found in private headers, which I've found to be mostly unreliable as the iOS versions change.

**Comment by blueneogeo** [comment]
Is it not possible to use UIKeyCommand? (https://developer.apple.com/documentation/uikit/uikeycommand)

**Comment by yoshisuga** [comment]
Yep, I think UIKeyCommand would work! I'll try to look into it.

**Comment by yoshisuga** [comment]
Sorry I've left this alone for awhile but I'm afraid we have to table this almost indefinitely.

The issue is that we need "key-up/down" events - we need to know when the button is pressed and then let go because that's what games need to know. Without it, we wouldn't be able to do the charge beam in R-Type, for example. UIKeyCommand doesn't seem to support this unfortunately. We don't have access to the lower level event handling for keyboard events, at least not easily.

**Comment by blueneogeo** [comment]
That's a shame, thanks for letting us know.
